---
influxdb-hosts:
  hosts:
    kafka-01:
      ansible_host: 10.20.10.122

all:
  vars:
    ansible_connection: ssh
    ansible_user:
    ansible_ssh_pass: ""
    ansible_become: true
    ansible_sudo_pass: ""
