---

- name: Install apt packages for Debian
  apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: yes

- name: Install pip packages for Debian
  pip:
    name: "{{ pip_packages }}"
    state: present