apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: default
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: dwpdigital/nifi-s3:latest
        resources:
          limits:
            memory: "4Gi"
            cpu: "500m"
        ports:
        - containerPort: 8443
        - containerPort: 8080
        - containerPort: 22
        env:
          - name: SINGLE_USER_CREDENTIALS_USERNAME
            value: "admin"
          - name: SINGLE_USER_CREDENTIALS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: nifi-password
          - name: NIFI_WEB_HTTP_PORT
            value: "8080"
          - name: NIFI_WEB_HTTPS_PORT
            value: "8443"
          - name: NIFI_WEB_HTTP_HOST
            value: "0.0.0.0"
          - name: AWS_S3_ENDPOINT
            value: "http://10.20.10.112:9001"
          - name: AWS_REGION
            value: "eu-west-2"
          - name: AWS_REGION_JAVA
            value: "EU_WEST_2"
          - name: S3_BUCKET
            value: "nifi"
          - name: AWS_ACCESS_KEY_ID
            value: "AKIAIOSFODNN7EXAMPLE"
          - name: AWS_SECRET_ACCESS_KEY
            value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

---
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: nifi-service      #+
spec:                     #+
  selector:               #+
    app: nifi             #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 8443      #+
    port: 8443            #+
    name: https           #+
  - protocol: TCP         #+
    targetPort: 8080      #+
    port: 8080            #+
    name: http            #+
  - protocol: TCP         #+
    targetPort: 22        #+
    port: 22              #+
    name: ssh             #+
  type: LoadBalancer      #+

#apiVersion: v1
#kind: Service
#metadata:
#  name: nifi-svc
#  namespace: default
#spec:
#  selector:
#    app: nifi
#  ports:
#  - port: 8443
#    targetPort: 8443
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: nifi
#  namespace: default
#  labels:
#    name: nifi
#  annotations:
#    nginx.ingress.kubernetes.io/proxy-send-timeout: '200'
#    nginx.ingress.kubernetes.io/proxy-read-timeout: '200'
#    nginx.ingress.kubernetes.io/proxy-connect-timeout: '200'
#    cert-manager.io/cluster-issuer: lets-encrypt-prod
#spec:
#  rules:
#    - host: k8s-main
#      http:
#        paths:
#          - path: "/"
#            pathType: Prefix
#            backend:
#              service:
#                name: nifi-svc
#                port:
#                  number: 8443
#  tls:
#    - hosts:
#        - k8s-main
#      secretName: nifi-secret-tls
