apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifiregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifiregistry
  template:
    metadata:
      labels:
        app: nifiregistry
    spec:
      containers:
      - name: nifiregistry-container
        image: michalklempa/nifi-registry:latest
        ports:
        - containerPort: 18080
          name: http
        - containerPort: 22
          name: ssh
        resources:
          requests:
            cpu: ".5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: VERSION
          value: "11"
        - name: NIFI_REGISTRY_WEB_HTTP_PORT
          value: "18080"
        - name: FLOW_PROVIDER
          value: "git"
        - name: GIT_REMOTE_URL
          value: "https://github.com/vladimirrodkin/etag_nifi_registry.git"
        - name: GIT_CHECKOUT_BRANCH
          value: "main"
        - name: FLOW_PROVIDER_GIT_FLOW_STORAGE_DIRECTORY
          value: "/opt/nifi-registry/flow-storage-git"
        - name: FLOW_PROVIDER_GIT_REMOTE_TO_PUSH
          value: "origin"
        - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_USER
          value: "vladimirrodkin"
        - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_PASSWORD
          value: "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"
        - name: GIT_CONFIG_USER_NAME
          value: "APACHE NIFI REGISTRY"
        - name: GIT_CONFIG_USER_EMAIL
          value: ""
---
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: nifiregistry-service     #+
spec:                     #+
  selector:               #+
    app: nifiregistry     #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 18080     #+
    port: 18080           #+
    name: http            #+
  - protocol: TCP         #+
    targetPort: 22        #+
    port: 22              #+
    name: ssh             #+
  type: LoadBalancer      #+