apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-config
data:
  nifi.properties: |
    nifi.flow.configuration.file=./conf/flow.xml.gz
    nifi.flow.configuration.archive.enabled=true
    nifi.flow.configuration.archive.dir=./conf/archive/
    nifi.flow.configuration.archive.max.time=30 days
    nifi.flow.configuration.archive.max.storage=500 MB
    nifi.flow.configuration.archive.max.count=
    nifi.flowcontroller.autoResumeState=true
    nifi.flowcontroller.graceful.shutdown.period=10 sec
    nifi.flowservice.writedelay.interval=500 ms
    nifi.administrative.yield.duration=30 sec
    nifi.bored.yield.duration=10 millis
    nifi.queue.backpressure.count=10000
    nifi.queue.backpressure.size=1 GB

    nifi.authorizer.configuration.file=./conf/authorizers.xml
    nifi.login.identity.provider.configuration.file=./conf/login-identity-providers.xml
    nifi.templates.directory=./conf/templates
    nifi.ui.banner.text=
    nifi.ui.autorefresh.interval=30 sec
    nifi.nar.library.directory=./lib
    nifi.nar.library.autoload.directory=./extensions
    nifi.nar.working.directory=./work/nar/
    nifi.documentation.working.directory=./work/docs/components
    nifi.state.management.configuration.file=./conf/state-management.xml
    nifi.state.management.provider.local=local-provider
    nifi.state.management.provider.cluster=zk-provider
    nifi.state.management.embedded.zookeeper.start=false
    nifi.state.management.embedded.zookeeper.properties=./conf/zookeeper.properties
    nifi.database.directory=./database_repository
    nifi.h2.url.append=;LOCK_TIMEOUT=25000;WRITE_DELAY=0;AUTO_SERVER=FALSE
    nifi.repository.encryption.protocol.version=
    nifi.repository.encryption.key.id=
    nifi.repository.encryption.key.provider=
    nifi.repository.encryption.key.provider.keystore.location=
    nifi.repository.encryption.key.provider.keystore.password=
    nifi.flowfile.repository.implementation=org.apache.nifi.controller.repository.WriteAheadFlowFileRepository
    nifi.flowfile.repository.wal.implementation=org.apache.nifi.wali.SequentialAccessWriteAheadLog
    nifi.flowfile.repository.directory=./flowfile_repository
    nifi.flowfile.repository.checkpoint.interval=20 secs
    nifi.flowfile.repository.always.sync=false
    nifi.flowfile.repository.retain.orphaned.flowfiles=true
    nifi.swap.manager.implementation=org.apache.nifi.controller.FileSystemSwapManager
    nifi.queue.swap.threshold=20000
    nifi.content.repository.implementation=org.apache.nifi.controller.repository.FileSystemRepository
    nifi.content.claim.max.appendable.size=1 MB
    nifi.content.repository.directory.default=./content_repository
    nifi.content.repository.archive.max.retention.period=7 days
    nifi.content.repository.archive.max.usage.percentage=50%
    nifi.content.repository.archive.enabled=true
    nifi.content.repository.always.sync=false
    nifi.content.viewer.url=../nifi-content-viewer/
    nifi.provenance.repository.implementation=org.apache.nifi.provenance.WriteAheadProvenanceRepository
    nifi.provenance.repository.directory.default=./provenance_repository
    nifi.provenance.repository.max.storage.time=30 days
    nifi.provenance.repository.max.storage.size=10 GB
    nifi.provenance.repository.rollover.time=10 mins
    nifi.provenance.repository.rollover.size=100 MB
    nifi.provenance.repository.query.threads=2
    nifi.provenance.repository.index.threads=2
    nifi.provenance.repository.compress.on.rollover=true
    nifi.provenance.repository.always.sync=false
    nifi.provenance.repository.indexed.fields=EventType, FlowFileUUID, Filename, ProcessorID, Relationship
    nifi.provenance.repository.indexed.attributes=
    nifi.provenance.repository.index.shard.size=500 MB
    nifi.provenance.repository.max.attribute.length=65536
    nifi.provenance.repository.concurrent.merge.threads=2
    nifi.provenance.repository.buffer.size=100000
    nifi.components.status.repository.implementation=org.apache.nifi.controller.status.history.VolatileComponentStatusRepository
    nifi.components.status.repository.buffer.size=1440
    nifi.components.status.snapshot.frequency=1 min
    nifi.status.repository.questdb.persist.node.days=14
    nifi.status.repository.questdb.persist.component.days=3
    nifi.status.repository.questdb.persist.location=./status_repository
    nifi.remote.input.host=
    nifi.remote.input.secure=false
    nifi.remote.input.socket.port=10000
    nifi.remote.input.http.enabled=true
    nifi.remote.input.http.transaction.ttl=30 sec
    nifi.remote.contents.cache.expiration=30 secs
    nifi.web.http.host=0.0.0.0
    nifi.web.http.port=8080
    nifi.web.http.network.interface.default=
    nifi.web.https.host=
    nifi.web.https.port=
    nifi.web.https.network.interface.default=
    nifi.web.jetty.working.directory=./work/jetty
    nifi.web.jetty.threads=200
    nifi.web.max.header.size=16 KB
    nifi.web.proxy.context.path=
    nifi.web.proxy.host=
    nifi.web.max.content.size=
    nifi.web.max.requests.per.second=30000
    nifi.web.max.access.token.requests.per.second=25
    nifi.web.request.timeout=60 secs
    nifi.web.request.ip.whitelist=
    nifi.web.should.send.server.version=true
    nifi.web.https.ciphersuites.include=
    nifi.web.https.ciphersuites.exclude=
    nifi.sensitive.props.key=7pw42GQY45W1Ln9RLuID4vawWoOeeeCM
    nifi.sensitive.props.key.protected=
    nifi.sensitive.props.algorithm=NIFI_PBKDF2_AES_GCM_256
    nifi.sensitive.props.additional.keys=
    nifi.security.autoreload.enabled=false
    nifi.security.autoreload.interval=10 secs
    nifi.security.keystore=
    nifi.security.keystoreType=
    nifi.security.keystorePasswd=
    nifi.security.keyPasswd=
    nifi.security.truststore=
    nifi.security.truststoreType=
    nifi.security.truststorePasswd=
    nifi.security.user.authorizer=single-user-authorizer
    nifi.security.allow.anonymous.authentication=false
    nifi.security.user.login.identity.provider=
    nifi.security.user.jws.key.rotation.period=PT1H
    nifi.security.ocsp.responder.url=
    nifi.security.ocsp.responder.certificate=

    nifi.security.user.oidc.discovery.url=
    nifi.security.user.oidc.connect.timeout=5 secs
    nifi.security.user.oidc.read.timeout=5 secs
    nifi.security.user.oidc.client.id=
    nifi.security.user.oidc.client.secret=
    nifi.security.user.oidc.preferred.jwsalgorithm=
    nifi.security.user.oidc.additional.scopes=
    nifi.security.user.oidc.claim.identifying.user=
    nifi.security.user.oidc.fallback.claims.identifying.user=

    nifi.security.user.knox.url=
    nifi.security.user.knox.publicKey=
    nifi.security.user.knox.cookieName=hadoop-jwt
    nifi.security.user.knox.audiences=

    nifi.security.user.saml.idp.metadata.url=
    nifi.security.user.saml.sp.entity.id=
    nifi.security.user.saml.identity.attribute.name=
    nifi.security.user.saml.group.attribute.name=
    nifi.security.user.saml.metadata.signing.enabled=false
    nifi.security.user.saml.request.signing.enabled=false
    nifi.security.user.saml.want.assertions.signed=true
    nifi.security.user.saml.signature.algorithm=http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
    nifi.security.user.saml.signature.digest.algorithm=http://www.w3.org/2001/04/xmlenc#sha256
    nifi.security.user.saml.message.logging.enabled=false
    nifi.security.user.saml.authentication.expiration=12 hours
    nifi.security.user.saml.single.logout.enabled=false
    nifi.security.user.saml.http.client.truststore.strategy=JDK
    nifi.security.user.saml.http.client.connect.timeout=30 secs
    nifi.security.user.saml.http.client.read.timeout=30 secs

    #nifi.security.identity.mapping.pattern.dn=^CN=(.*?), OU=(.*?), O=(.*?), L=(.*?), ST=(.*?), C=(.*?)$
    #nifi.security.identity.mapping.value.dn=$1@$2
    #nifi.security.identity.mapping.transform.dn=NONE
    #nifi.security.identity.mapping.pattern.kerb=^(.*?)/instance@(.*?)$
    #nifi.security.identity.mapping.value.kerb=$1@$2
    #nifi.security.identity.mapping.transform.kerb=UPPER
    #nifi.security.group.mapping.pattern.anygroup=^(.*)$
    #nifi.security.group.mapping.value.anygroup=$1
    #nifi.security.group.mapping.transform.anygroup=LOWER

    nifi.cluster.protocol.heartbeat.interval=5 sec
    nifi.cluster.protocol.heartbeat.missable.max=8
    nifi.cluster.protocol.is.secure=false

    nifi.cluster.is.node=false
    nifi.cluster.node.address=nifi-f774c768f-zs67c
    nifi.cluster.node.protocol.port=
    nifi.cluster.node.protocol.max.threads=50
    nifi.cluster.node.event.history.size=25
    nifi.cluster.node.connection.timeout=5 sec
    nifi.cluster.node.read.timeout=5 sec
    nifi.cluster.node.max.concurrent.requests=100
    nifi.cluster.firewall.file=
    nifi.cluster.flow.election.max.wait.time=5 mins
    nifi.cluster.flow.election.max.candidates=

    nifi.cluster.load.balance.host=
    nifi.cluster.load.balance.port=6342
    nifi.cluster.load.balance.connections.per.node=1
    nifi.cluster.load.balance.max.thread.count=8
    nifi.cluster.load.balance.comms.timeout=30 sec

    nifi.zookeeper.connect.string=
    nifi.zookeeper.connect.timeout=10 secs
    nifi.zookeeper.session.timeout=10 secs
    nifi.zookeeper.root.node=/nifi
    nifi.zookeeper.client.secure=false
    nifi.zookeeper.security.keystore=
    nifi.zookeeper.security.keystoreType=
    nifi.zookeeper.security.keystorePasswd=
    nifi.zookeeper.security.truststore=
    nifi.zookeeper.security.truststoreType=
    nifi.zookeeper.security.truststorePasswd=
    nifi.zookeeper.jute.maxbuffer=

    nifi.zookeeper.auth.type=
    nifi.zookeeper.kerberos.removeHostFromPrincipal=
    nifi.zookeeper.kerberos.removeRealmFromPrincipal=

    nifi.kerberos.krb5.file=

    nifi.kerberos.service.principal=
    nifi.kerberos.service.keytab.location=

    nifi.kerberos.spnego.principal=
    nifi.kerberos.spnego.keytab.location=
    nifi.kerberos.spnego.authentication.expiration=12 hours

    nifi.variable.registry.properties=18080

    nifi.analytics.predict.enabled=false
    nifi.analytics.predict.interval=3 mins
    nifi.analytics.query.interval=5 mins
    nifi.analytics.connection.model.implementation=org.apache.nifi.controller.status.analytics.models.OrdinaryLeastSquares
    nifi.analytics.connection.model.score.name=rSquared
    nifi.analytics.connection.model.score.threshold=.90

    nifi.monitor.long.running.task.schedule=
    nifi.monitor.long.running.task.threshold=

    nifi.diagnostics.on.shutdown.enabled=false

    nifi.diagnostics.on.shutdown.verbose=false

    nifi.diagnostics.on.shutdown.directory=./diagnostics

    nifi.diagnostics.on.shutdown.max.filecount=10

    nifi.diagnostics.on.shutdown.max.directory.size=10 MB
