apiVersion: v1
kind: Secret
metadata:
  name: nifi-secrets
type: Opaque
data:
  git_username: dmxhZGltaXJyb2RraW4=
  git_password: Z2hwX29IRlFpTko2eWpJWXptVEZvQ1NKVFllc1VoeklCdzJDZ1FhWA==
  s3_username: YWRtaW4=
  s3_password: MzU3ODE0MTY=
  nifi_username: YWRtaW4=
  nifi_password: ZXRhZ25pZmlhZG1pbg==
  nifi_sensitive_props_key: MDEyMzQ1Njc4OTAx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  namespace: default
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      volumes:
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
      - name: nifi-data
        hostPath:
          path: /mnt/nifi_data
      containers:
      - name: s3fs
        image: efrecon/s3fs:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /dev/fuse
          name: dev-fuse
        - mountPath: /opt/s3fs/bucket:shared
          name: nifi-data
        securityContext:
          privileged: true
        command: ["/bin/sh","-c"]
        args: ["AWS_S3_AUTHFILE=/opt/s3fs/passwd-s3fs; echo ${AWS_S3_ACCESS_KEY_ID}:${AWS_S3_SECRET_ACCESS_KEY} > ${AWS_S3_AUTHFILE};  chmod a+rw /opt/s3fs/bucket; chmod 600 ${AWS_S3_AUTHFILE}; s3fs $DEBUG_OPTS -o passwd_file=$AWS_S3_AUTHFILE -o url=$AWS_S3_URL -o $S3FS_ARGS  $AWS_S3_BUCKET $AWS_S3_MOUNT; ls.sh"]
        env:
          - name: AWS_S3_BUCKET
            value: "nifi"
          - name: AWS_S3_URL
            value: "http://10.20.10.112:9001"
          - name: AWS_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: s3_username
          - name: AWS_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: s3_password
          - name: S3FS_ARGS
            value: "nonempty,use_path_request_style,allow_other,umask=0000,mp_umask=0000"
          - name: S3FS_DEBUG
            value: "0"
      - name: nifiregistry
        image: michalklempa/nifi-registry:latest
        ports:
        - containerPort: 18080
          name: http
        volumeMounts:
        - mountPath: /opt/nifi-registry/nifi-registry-0.8.0/database
          name: nifi-data
          subPath: registry/database
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: ".5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: VERSION
          value: "11"
        - name: NIFI_REGISTRY_WEB_HTTP_PORT
          value: "18080"
        - name: FLOW_PROVIDER
          value: "git"
        - name: GIT_REMOTE_URL
          value: "https://github.com/vladimirrodkin/etag_nifi_registry.git"
        - name: GIT_CHECKOUT_BRANCH
          value: "main"
        - name: FLOW_PROVIDER_GIT_FLOW_STORAGE_DIRECTORY
          value: "/opt/nifi-registry/flow-storage-git"
        - name: FLOW_PROVIDER_GIT_REMOTE_TO_PUSH
          value: "origin"
        - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_USER
          valueFrom:
            secretKeyRef:
              name: nifi-secrets
              key: git_username
        - name: FLOW_PROVIDER_GIT_REMOTE_ACCESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nifi-secrets
              key: git_password
        - name: GIT_CONFIG_USER_NAME
          value: "APACHE NIFI REGISTRY"
        - name: GIT_CONFIG_USER_EMAIL
          value: ""
      - name: nifi
        image: apache/nifi:latest
        resources:
          limits:
            memory: "4Gi"
            cpu: "500m"
        ports:
        - containerPort: 8443
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/nifi/nifi-current/conf
          name: nifi-data
          subPath: conf
        - mountPath: /opt/nifi/nifi-current/logs
          name: nifi-data
          subPath: logs
        - mountPath: /opt/nifi/nifi-current/state
          name: nifi-data
          subPath: state
        - mountPath: /opt/nifi/nifi-current/extensions
          name: nifi-data
          subPath: extensions
        - mountPath: /opt/nifi/nifi-current/content_repository
          name: nifi-data
          subPath: content_repository
        - mountPath: /opt/nifi/nifi-current/database_repository
          name: nifi-data
          subPath: database_repository
        - mountPath: /opt/nifi/nifi-current/flowfile_repository
          name: nifi-data
          subPath: flowfile_repository
        - mountPath: /opt/nifi/nifi-current/provenance_repository
          name: nifi-data
          subPath: provenance_repository
        securityContext:
          privileged: true
        env:
          - name: SINGLE_USER_CREDENTIALS_USERNAME
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: nifi_username
          - name: SINGLE_USER_CREDENTIALS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: nifi_password
          - name: NIFI_SENSITIVE_PROPS_KEY
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: nifi_sensitive_props_key
          - name: NIFI_WEB_HTTP_PORT
            value: "8080"
          - name: NIFI_WEB_HTTPS_PORT
            value: "8443"
          - name: NIFI_WEB_HTTP_HOST
            value: "0.0.0.0"
---
kind: Service
apiVersion: v1
metadata:
  name: nifi
spec:
  selector:
    app: nifi
  ports:
  - protocol: TCP
    targetPort: 18080
    port: 18080
    name: http-registry
  - protocol: TCP
    targetPort: 8080
    port: 8080
    name: http-nifi
  - protocol: TCP
    targetPort: 8443
    port: 8443
    name: https-nifi
  type: LoadBalancer
