apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3fs
  namespace: default
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: s3fs
        image: efrecon/s3fs:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
        - mountPath: /dev/fuse
          name: dev-fuse
        securityContext:
          privileged: true
        command: ["ls.sh"]
        env:
          - name: AWS_S3_BUCKET
            value: "nifi"
          - name: AWS_S3_URL
            value: "http://10.20.10.106:9000"
          - name: AWS_S3_ACCESS_KEY_ID
            value: "admin"
          - name: AWS_S3_SECRET_ACCESS_KEY
            value: "12345678"
      volumes:
        - name: dev-fuse
          hostPath:
            path: /dev/fuse