---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Debian
    image: jrei/systemd-debian:11
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      #vault_password_file: "<ansible-vault-file-path>"
      vault_password_file: "~/Keys/vault_pass"
verifier:
  name: testinfra
